@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title PUT Method - Backend Only

autonumber

actor "Frontend" as Frontend
participant "<<component>> Controller " as Controller
participant "<<component>> Service" as BackendService
participant "<<component>> Repository" as Repository

activate Frontend

    Frontend -> Controller : Sends HTTP PUT request
    activate Controller

        Controller -> BackendService** : instantiates service

        Controller -> BackendService : Requests to replace data
        activate BackendService

            BackendService -> Repository** : instantiates repository

            BackendService -> Repository : Replaces data
            activate Repository

                Repository --> BackendService : Success or Failure
            deactivate Repository

        BackendService --> Controller : Return Success or Failure
        deactivate BackendService

    Controller --> Frontend : Return Success or Failure
    deactivate Controller

deactivate Frontend

@enduml
