@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Delete Method - Backend Only

autonumber

actor "Frontend" as Frontend
participant "<<component>> Controller " as Controller
participant "<<component>> Service" as BackendService
participant "<<component>> Repository" as Repository

activate Frontend

    Frontend -> Controller : Sends HTTP DELETE request
    activate Controller
    
        Controller -> BackendService** : creates service

        Controller -> BackendService : Requests to delete item
        activate BackendService
        
            BackendService -> Repository** : creates repository

            BackendService -> Repository : Deletes item
            activate Repository

                Repository --> BackendService : Success or Failure
            deactivate Repository

        BackendService --> Controller : Return Success or Failure
        deactivate BackendService

    Controller --> Frontend : Return Success or Failure
    deactivate Controller

deactivate Frontend

@enduml
