@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Patch Method - Level 3

autonumber

participant "Frontend" as FE
participant "BackEnd" as BE
database "Mongo Database" as DB


    activate FE

        FE -> BE : Requests patch operation
        activate BE

        BE -> DB : Update something
        activate DB

        DB --> BE : Return updated \ninformation
        deactivate DB


            BE --> FE : Return OK or Error
            deactivate BE


        deactivate FE


@enduml
